import { App, Button, DatePicker, Form, InputNumber, Modal, Select } from "antd";
import { useState } from "react";
import { bookingService } from "../services/api";
import Title from "antd/es/typography/Title";
import Text from "antd/es/typography/Text";
import Input from "antd/es/input/Input";
import { BarcodeOutlined, DollarOutlined } from "@ant-design/icons";

interface AddTicketModalProps {
    isOpen: boolean;
    onClose: () => void;
    onRefresh: () => void;
}

export default function AddTicketModal({ isOpen, onClose, onRefresh }: AddTicketModalProps) {
    const [form] = Form.useForm();
    const { message } = App.useApp();
    const [isSubmitting, setIsSubmitting] = useState(false);

    const handleSubmit = async (values: any) => {
        setIsSubmitting(true);
        try {
            const payload = {
                ...values,
                eventDate: values.eventDate.toISOString(),
            };

            await bookingService.addTicket(payload);
            message.success("Ticket published successfully!");
            form.resetFields();
            onClose();
            onRefresh();
        } catch (err: any) {
            message.error(err.detail || "Failed to add ticket");
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <Modal
            title={<Title level={4} className="m-0 text-acceloka-text!">Publish New Ticket</Title>}
            open={isOpen}
            onCancel={onClose}
            footer={null}
            centered
            width={520}
            className="acceloka-modal"
        >
            <Form
                form={form}
                layout="vertical"
                onFinish={handleSubmit}
                className="mt-6"
                requiredMark={false}
            >
                <Form.Item
                    name="ticketName"
                    label={<Text strong className="text-acceloka-muted! text-[10px] uppercase tracking-widest">Event Name</Text>}
                    rules={[{ required: true, message: 'Required' }]}
                >
                    <Input placeholder="e.g. Jakarta Jazz Festival" className="h-11 rounded-xl! bg-acceloka-bg! border-acceloka-border! text-acceloka-text!" />
                </Form.Item>

                {/* Note: TicketCode is removed here as it is auto-generated by backend rule [First Letter]-[ID] */}
                <Form.Item
                    name="categoryName"
                    label={<Text strong className="text-acceloka-muted! text-[10px] uppercase tracking-widest">Category</Text>}
                    rules={[{ required: true, message: 'Select a category' }]}
                >
                    <Select placeholder="Select Category" className="h-11 w-full rounded-xl!">
                        <Select.Option value="Concert">Concert</Select.Option>
                        <Select.Option value="Sports">Sports</Select.Option>
                        <Select.Option value="Festival">Festival</Select.Option>
                        <Select.Option value="Exhibition">Exhibition</Select.Option>
                    </Select>
                </Form.Item>

                <Form.Item
                    name="eventDate"
                    label={<Text strong className="text-acceloka-muted! text-[10px] uppercase tracking-widest">Event Date & Time</Text>}
                    rules={[{ required: true }]}
                >
                    <DatePicker
                        showTime
                        placeholder="Select date and time"
                        className="w-full h-11 rounded-xl! bg-acceloka-bg! border-acceloka-border! text-acceloka-text!"
                    />
                </Form.Item>

                <div className="grid grid-cols-2 gap-4">
                    <Form.Item
                        name="price"
                        label={<Text strong className="text-acceloka-muted! text-[10px] uppercase tracking-widest">Price (IDR)</Text>}
                        rules={[{ required: true }]}
                    >
                        <InputNumber
                            placeholder="0"
                            className="w-full h-11 flex items-center rounded-xl! bg-acceloka-bg! border-acceloka-border! text-acceloka-text!"
                            prefix={<DollarOutlined className="text-acceloka-blue!" />}
                            min={1}
                        />
                    </Form.Item>

                    <Form.Item
                        name="quota"
                        label={<Text strong className="text-acceloka-muted! text-[10px] uppercase tracking-widest">Quota</Text>}
                        rules={[{ required: true }]}
                    >
                        <InputNumber placeholder="100" min={1} className="w-full h-11 flex items-center rounded-xl! bg-acceloka-bg! border-acceloka-border! text-acceloka-text!" />
                    </Form.Item>
                </div>

                <div className="flex gap-3 mt-8">
                    <Button block onClick={onClose} className="h-12 rounded-xl! font-bold! border-acceloka-border! text-acceloka-muted!">Cancel</Button>
                    <Button type="primary" block htmlType="submit" loading={isSubmitting} className="h-12 rounded-xl! font-bold! bg-acceloka-blue! border-none!">Publish Ticket</Button>
                </div>
            </Form>
        </Modal>
    );
};